### PR TITLE
docs: add instructions for arch linux

### PR DESCRIPTION
**Pull request by orhun**
let's go baby

<https://archlinux.org/packages/extra/x86_64/ttysvr/>

### CODE REVIEW

**Comment by cdkw2** [comment]
ummm what?

**Comment by orhun** [comment]
Sorry for not being clear here, I packaged `ttysvr` for Arch Linux which means the binary is now officially available for users. This PR simply adds instructions for installing this package.

**Comment by HarshalRathore** [comment]
i thought it would be added to aur but it's in official repos already

**Comment by cdkw2** [comment]
I was gonna make it available on aur but you did even better, thanks!

**Comment by HarshalRathore** [comment]
> I was gonna make it available on aur but you did even better, thanks!

I was almost finished with PKGBUILD for AUR but then saw this pull request

**Comment by cxreiff** [comment]
Thank you as always Orhun. :)

**Pull request merged**
